version: "3"
services:
  db:
    image: rethinkdb:latest
    ports:
      - "38080:8080"
      - "38015:28015"
      - "39015:29015"
  atlas:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/app/atlas/src
      - /home/app/atlas/src/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_KEY=${JWT_KEY}
    depends_on:
          - db
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  prestashop:
    image: 'bitnami/prestashop:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'prestashop_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - PRESTASHOP_HOST=localhost

volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local